### ISSUE TITLE
Update Readme: must sync db before running seeds

### ISSUE THREAD

**Issue by mansiagarwal451** [coding-blocks/trouble-maker#14]
When setting up the project, there is no 'users' table defined in the database, but we intend to insert values in the table, which creates an error `ERROR: relation "users" does not exist`.

**Comment by abhishek97** [comment]
You need to db.sync() first! 
I see the readme doesn't cover this, please update the readme accordingly

**Comment by abhishek97** [comment]
Btw, you may claim 20 bounty points for finding this issue

**Comment by Rish-Singhal** [comment]
updated :+1: PR#17

**Comment by mansiagarwal451** [comment]
Thanks. When we go to the claims page (https://boss.codingblocks.com/claims/add), it shows an error `Error, please report this to admin at codingblocks.com`. I am logged in and have also connected my github at account.codingblocks.com. There is an option for only viewing claims and not adding any claims in the navigation bar.

**Comment by abhishek97** [comment]
@mansiagarwal451 Make sure you are loggedIn, have verified your email and have connected your github. If not dm me on gitter.

**Comment by mansiagarwal451** [comment]
Yes, that issue has been resolved.
