### ISSUE TITLE
Feature: Add tags support

### ISSUE THREAD

**Issue by abhishek97** [coding-blocks/trouble-maker#19]
It would be easy to add tags to questions to easily find them.

Schema 

```
tags
id | name | createdBy | createdAt | updatedAt
```

```
question_tags
id | tagId | questionId | createdAt | updatedAt
```

API to implement
- [ ] POST /tags
- [ ] GET /tags
- [ ] Make sure we can include tag with questions. i.e they are related 
- [ ] Make the /questions api support `filter: { tags: [ 12, 34 ] }` query param.

The frontend part of this feature is explained here: https://github.com/coding-blocks/trouble-maker-frontend/issues/18 and the bounty is for combined feature implementation.

**Comment by wildcod** [comment]
I want to implement this so can I do?

**Comment by Manit1** [comment]
@abhishek97 Taking up this task !

**Comment by chanda1998** [comment]
is this issue still open

**Comment by abhishek97** [comment]
Yes it is

**Comment by HardikSo** [comment]
is this issue still open?

**Comment by abhishek97** [comment]
Yes it is

**Comment by predatorcoderr** [comment]
is anyone working on this issue and please provide some further details of the issue

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
@abhishek97 is this still up for grab? can i get it done

So the main idea is to use the existing schema to create get/post apis?
