### ISSUE TITLE
Create Preview Quiz View

### ISSUE THREAD

**Issue by jatinkatyal13** [coding-blocks/trouble-maker#30]
Currently, we don't have any route to preview the quiz with the options that we've created. Create a route `/quiz/<id>/preview` which has a similar UI to the following Image
<img width="1792" alt="Screenshot 2020-05-27 at 5 07 11 PM" src="https://user-images.githubusercontent.com/18536540/83014550-8fd7fc00-a03c-11ea-8747-c38e8c9b444c.png">

Use `question` as a query param to index the questions in the quiz.

*Submission Guidelines*
- Online one person will be assigned this issue and will be tagged as the Assignee
- Connect me over Discord online-codingblocks channel or share your approach in the comments
- User Ember CLI rather than creating the files manually
- Attach screenshot/GIF of the final result before submitting the PR
- Once assigned start with a WIP PR and add @jatinkatyal13 as the reviewer

*Pre-requisite*
- Basics HTML/CSS
- Basics of Ember JS

**Comment by atmanandsah** [comment]
@jatinkatyal13 bhaiya I would like to work on this Can you assignee to me?

**Comment by jatinkatyal13** [comment]
@atmanandsah sure let's start with how you gonna solve this?

**Comment by MohdImran001** [comment]
@jatinkatyal13 we have to create a route to preview the quiz that's why I guess this issue should come in trouble-maker-frontend repo

**Comment by atmanandsah** [comment]
@jatinkatyal13 bhaiya  can I know the what will be the functionality of the preview quiz.

**Comment by jatinkatyal13** [comment]
Moving the issue to the frontend repository [here](https://github.com/coding-blocks/trouble-maker-frontend/issues/29)
