### ISSUE TITLE
Add a flag "multipleCorrect" to questions

### ISSUE THREAD

**Issue by abhishek97** [coding-blocks/trouble-maker#6]
A question can be either multiple correct or single correct. 

- Add a flag to indicate this. "multipleCorrect" : Boolean
- if the question is single correct, only allow one `correctAnswers` or send an error.
- Add similar check when submitting a question and quiz.

**Comment by the-dagger** [comment]
@abhishek97 Could you look at the Bounty score again? 
I think that you meant to set it as 200 instead.

**Comment by abhishek97** [comment]
@the-dagger No, I meant 2000 only. This, if implemented completely is a lot of work. If you are looking at #8 and #9, none of these completely solve the issue yet.

**Comment by abhishek97** [comment]
Fixed in #10
